using System.Globalization;

namespace LinkShelf.Services;

public enum AppLanguage
{
    English,
    Chinese
}

public sealed class LocalizationService
{
    private AppLanguage language;

    public LocalizationService()
    {
        language = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("zh", StringComparison.OrdinalIgnoreCase)
            ? AppLanguage.Chinese
            : AppLanguage.English;
    }

    public AppLanguage Language
    {
        get => language;
        set => language = value;
    }

    public string T(string key)
    {
        var map = language == AppLanguage.Chinese ? Zh : En;
        return map.TryGetValue(key, out var value) ? value : key;
    }

    public string F(string key, params object[] args)
    {
        return string.Format(CultureInfo.CurrentCulture, T(key), args);
    }

    public string Code(string code)
    {
        if (string.IsNullOrWhiteSpace(code))
        {
            return "";
        }

        return T("code." + NormalizeCode(code));
    }

    private static string NormalizeCode(string code)
    {
        var normalized = code.StartsWith("code.", StringComparison.OrdinalIgnoreCase)
            ? code[5..]
            : code;

        return normalized switch
        {
            "导入现有缓存" => "complete-existing-link",
            "瀵煎叆鐜版湁缂撳瓨" => "complete-existing-link",
            _ => normalized
        };
    }

    private static readonly Dictionary<string, string> En = new()
    {
        ["app.title"] = "Link Shelf",
        ["app.startupFailed"] = "The application failed to start. A startup error log was written.",
        ["app.cannotLocateSelf"] = "The current executable cannot be located, so administrator elevation cannot be requested automatically.",
        ["app.adminRequired"] = "Administrator permission is required to move paths and create links.",

        ["main.cacheRoot"] = "Cache root: {0}",
        ["main.configFile"] = "Config file: {0}",
        ["main.add"] = "Add item",
        ["main.addRecommended"] = "Add recommended items",
        ["main.addDirectory"] = "Add directory",
        ["main.addFile"] = "Add file",
        ["main.restore"] = "Restore links",
        ["main.check"] = "Check status",
        ["main.revert"] = "Move back / Undo",
        ["main.project"] = "Project app",
        ["main.language"] = "Language",
        ["language.en"] = "English",
        ["language.zh"] = "Chinese",
        ["main.log"] = "Activity log",
        ["help.add"] = "Move a selected file or directory into this cache root, then create a link at its original path.",
        ["help.addRecommended"] = "Choose from detected common configuration and state paths on this computer.",
        ["help.addDirectory"] = "Move a selected directory into this cache root, then link it back to its original path.",
        ["help.addFile"] = "Move a selected file into this cache root, then link it back to its original path.",
        ["help.restore"] = "Create local links from the saved configuration. If rows are selected, only those rows are processed.",
        ["help.check"] = "Check the configuration, cache items, and target links without moving files.",
        ["help.revert"] = "Move selected cache items back to their original paths, remove their links, delete them from the cache, and remove their config records.",
        ["help.project"] = "Create a hard link to LinkShelf.exe in another folder. When launched from that folder, the linked program uses that folder as its own cache root.",

        ["grid.cacheName"] = "Cache name",
        ["grid.originalPath"] = "Original path",
        ["grid.type"] = "Type",
        ["grid.status"] = "Status",
        ["grid.checkResult"] = "Check result",
        ["grid.sourceMachine"] = "Source machine",
        ["grid.lastOperation"] = "Last operation",
        ["grid.updatedAt"] = "Updated at",
        ["grid.cachePath"] = "Cache path",
        ["grid.localTarget"] = "Local target",

        ["dialog.pickDirectory"] = "Choose a directory to move into the cache",
        ["dialog.pickFile"] = "Choose a file to move into the cache",
        ["dialog.pickProjectionDirectory"] = "Choose a folder to project Link Shelf into",
        ["dialog.noItems"] = "There are no sync items in the configuration.",
        ["dialog.noSelection"] = "Select one or more items first.",
        ["dialog.restoreSelected"] = "Restore {0} selected item(s).",
        ["dialog.restoreAll"] = "Restore all enabled items.",
        ["dialog.restoreConfirmSuffix"] = "Conflicts will be handled one item at a time.",
        ["dialog.revertConfirm"] = "Move {0} selected item(s) back to their original paths and remove their config records? This will delete the corresponding cache entries after they are moved back.",
        ["recommended.title"] = "Recommended items",
        ["recommended.heading"] = "Add recommended items",
        ["recommended.description"] = "Only paths that exist on this computer and are not already in the configuration are shown.",
        ["recommended.select"] = "Add",
        ["recommended.name"] = "Name",
        ["recommended.path"] = "Path",
        ["recommended.type"] = "Type",
        ["recommended.reason"] = "Why",
        ["recommended.addSelected"] = "Add selected",
        ["recommended.noItems"] = "No recommended item is currently available. Existing configured paths and missing local paths are hidden.",
        ["recommended.noSelection"] = "Select one or more recommended items first.",
        ["dialog.lockedPathTitle"] = "Path is in use",
        ["dialog.lockedPathMessage"] = "The add operation failed because this path may be used by another program.{0}{0}Path:{0}{1}{0}{0}Error:{0}{2}{0}{0}Detected programs:{0}{3}{0}{0}Close the listed software, then choose OK to scan again and continue. Choose Cancel to stop this add operation.",
        ["dialog.lockedPathPreflightMessage"] = "This path appears to be used by another program.{0}{0}Path:{0}{1}{0}{0}Detected programs:{0}{2}{0}{0}Close the listed software, then choose OK to scan again and continue. Choose Cancel to stop this add operation.",
        ["dialog.lockedPathNoProcesses"] = "No locking program was detected. The path may still be blocked by permissions, security software, or a running program.",
        ["dialog.lockedPathTimedOut"] = "The lock scan timed out before a complete result was available.",
        ["dialog.accessDeniedTitle"] = "Access denied",
        ["dialog.accessDeniedMessage"] = "Windows denied access while moving this path.{0}{0}Path:{0}{1}{0}{0}Error:{0}{2}{0}{0}This usually means the directory has protected permissions, a service is guarding it, or Windows refuses to move part of its contents. Close related software and services, or move a smaller subdirectory instead.",
        ["lockWindow.title"] = "Resolve file usage",
        ["lockWindow.heading"] = "Operation failed. Detecting processes that use this path.",
        ["lockWindow.path"] = "Path: {0}",
        ["lockWindow.error"] = "Windows error: {0}",
        ["lockWindow.scanning"] = "Getting locking information",
        ["lockWindow.noProcesses"] = "No locking process was found.",
        ["lockWindow.foundProcesses"] = "Found {0} locking process(es).",
        ["lockWindow.scanFailed"] = "Failed to get locking information: {0}",
        ["lockWindow.processName"] = "Process",
        ["lockWindow.processId"] = "PID",
        ["lockWindow.user"] = "User",
        ["lockWindow.executable"] = "Executable",
        ["lockWindow.terminateSelected"] = "Terminate selected processes",
        ["lockWindow.refresh"] = "Refresh",
        ["lockWindow.terminateAllContinue"] = "Terminate all and continue",
        ["lockWindow.terminating"] = "Terminating processes",
        ["lockWindow.terminateConfirmTitle"] = "Terminate processes",
        ["lockWindow.terminateConfirm"] = "Terminate {0} selected process(es)? Unsaved work in those programs may be lost.",
        ["lockWindow.terminateFailed"] = "Failed to terminate processes: {0}",

        ["conflict.title"] = "Resolve conflict",
        ["conflict.heading"] = "The target path has a conflict",
        ["conflict.target"] = "Target path: {0}",
        ["conflict.cache"] = "Cache path: {0}",
        ["conflict.useCache"] = "Use the content in this cache",
        ["conflict.useTarget"] = "Use the content at the original path",
        ["conflict.merge"] = "Keep both sides first, then merge what can be merged",
        ["conflict.skip"] = "Back up the original content and skip this item",
        ["conflict.cancel"] = "Cancel",

        ["log.started"] = "Application started.",
        ["log.begin"] = "Begin: {0}",
        ["log.done"] = "Done: {0}",
        ["log.failed"] = "Failed: {0}, {1}",
        ["log.retryLockedPath"] = "Retry after locked path prompt: {0}",
        ["log.lockedPathCanceled"] = "Canceled locked path operation: {0}",
        ["log.projected"] = "Projected app link: {0}",
        ["projection.created"] = "Created a projected LinkShelf.exe at: {0}. Launch that linked executable to use its folder as a separate cache root.",
        ["projection.cannotLocateSelf"] = "The current executable could not be located.",
        ["projection.error.sameExecutable"] = "The selected folder already resolves to the current executable location.",
        ["projection.error.targetExists"] = "The selected folder already contains LinkShelf.exe. Link Shelf will not overwrite it.",
        ["projection.error.differentDrive"] = "Projection uses a hard link, so the target folder must be on the same drive as the current LinkShelf.exe.",
        ["projection.error.nativeFailure"] = "Windows failed to create the projected hard link: {0}",
        ["op.addDirectory"] = "add-directory",
        ["op.addFile"] = "add-file",
        ["op.addRecommendedItem"] = "add-recommended-item: {0}",
        ["op.restoreLinks"] = "restore-links",
        ["op.checkStatus"] = "check-status",
        ["op.revertItems"] = "move-back-undo",

        ["code.directory"] = "Directory",
        ["code.file"] = "File",
        ["code.enabled"] = "Enabled",
        ["code.removed"] = "Removed",
        ["code.problem"] = "Problem",
        ["code.symbolic-link"] = "Symbolic link",
        ["code.ok"] = "OK",
        ["code.cache-missing"] = "Cache item missing",
        ["code.target-has-content"] = "Target has real content",
        ["code.target-missing-link"] = "Target link missing",
        ["code.link-wrong-target"] = "Link points elsewhere",
        ["code.skipped"] = "Skipped",
        ["code.restored"] = "Restored",
        ["code.add-sync-item"] = "Add sync item",
        ["code.complete-existing-link"] = "Complete existing link",
        ["code.restore-local-link"] = "Restore local link",
        ["code.revert-item"] = "Move back / undo",
        ["code.cache-already-exists"] = "A cache item with this name already exists.",
        ["code.target-is-another-link"] = "The target path is already a link to another location.",
        ["code.target-has-real-content"] = "The target path already has real content.",

        ["preset.codex.name"] = "Codex",
        ["preset.codex.reason"] = "Codex settings and local state for agent workflows.",
        ["preset.claude.name"] = "Claude",
        ["preset.claude.reason"] = "Claude Code settings and local state.",
        ["preset.claudeJson.name"] = "Claude JSON",
        ["preset.claudeJson.reason"] = "Claude Code user-level configuration file.",
        ["preset.claudeDesktop.name"] = "Claude Desktop",
        ["preset.claudeDesktop.reason"] = "Claude Desktop settings, MCP configuration, and local application state.",
        ["preset.claudeDesktopMsix.name"] = "Claude Desktop MSIX",
        ["preset.claudeDesktopMsix.reason"] = "Claude Desktop packaged-app settings and MCP configuration location used by recent Windows installs.",
        ["preset.gemini.name"] = "Gemini",
        ["preset.gemini.reason"] = "Gemini CLI settings and local state.",
        ["preset.continue.name"] = "Continue",
        ["preset.continue.reason"] = "Continue.dev assistant configuration, model settings, rules, and local state.",
        ["preset.aiderConfig.name"] = "aider config",
        ["preset.aiderConfig.reason"] = "User-level aider YAML configuration.",
        ["preset.windsurfMcp.name"] = "Windsurf MCP",
        ["preset.windsurfMcp.reason"] = "Windsurf Cascade MCP configuration and related Codeium state.",
        ["preset.windsurfUser.name"] = "Windsurf user settings",
        ["preset.windsurfUser.reason"] = "Windsurf editor settings, keybindings, snippets, and user state.",
        ["preset.cursorProfile.name"] = "Cursor profile",
        ["preset.cursorProfile.reason"] = "Cursor profile data under the user folder.",
        ["preset.cursorUser.name"] = "Cursor user settings",
        ["preset.cursorUser.reason"] = "Cursor settings, keybindings, snippets, and user state.",
        ["preset.cursorBackups.name"] = "Cursor backups",
        ["preset.cursorBackups.reason"] = "Cursor workspace backup data.",
        ["preset.cursorWorkspaces.name"] = "Cursor workspaces",
        ["preset.cursorWorkspaces.reason"] = "Cursor workspace metadata.",
        ["preset.cursorDictionaries.name"] = "Cursor dictionaries",
        ["preset.cursorDictionaries.reason"] = "Cursor custom dictionaries.",
        ["preset.clineCursor.name"] = "Cline for Cursor",
        ["preset.clineCursor.reason"] = "Cline extension state and task history inside Cursor.",
        ["preset.rooCursor.name"] = "Roo Code for Cursor",
        ["preset.rooCursor.reason"] = "Roo Code extension state, modes, settings, and task history inside Cursor.",
        ["preset.vscodeProfile.name"] = "VS Code profile",
        ["preset.vscodeProfile.reason"] = "VS Code extensions and profile data under the user folder.",
        ["preset.vscodeUser.name"] = "VS Code user settings",
        ["preset.vscodeUser.reason"] = "VS Code settings, keybindings, snippets, and user state.",
        ["preset.vscodeInsidersProfile.name"] = "VS Code Insiders profile",
        ["preset.vscodeInsidersProfile.reason"] = "VS Code Insiders extensions and profile data under the user folder.",
        ["preset.vscodeInsidersUser.name"] = "VS Code Insiders user settings",
        ["preset.vscodeInsidersUser.reason"] = "VS Code Insiders settings, keybindings, snippets, and user state.",
        ["preset.vscodiumProfile.name"] = "VSCodium profile",
        ["preset.vscodiumProfile.reason"] = "VSCodium extensions and profile data under the user folder.",
        ["preset.vscodiumUser.name"] = "VSCodium user settings",
        ["preset.vscodiumUser.reason"] = "VSCodium settings, keybindings, snippets, and user state.",
        ["preset.clineVsCode.name"] = "Cline for VS Code",
        ["preset.clineVsCode.reason"] = "Cline extension state and task history inside VS Code.",
        ["preset.rooVsCode.name"] = "Roo Code for VS Code",
        ["preset.rooVsCode.reason"] = "Roo Code extension state, modes, settings, and task history inside VS Code.",
        ["preset.copilotVsCode.name"] = "GitHub Copilot for VS Code",
        ["preset.copilotVsCode.reason"] = "GitHub Copilot extension state inside VS Code.",
        ["preset.copilotChatVsCode.name"] = "GitHub Copilot Chat for VS Code",
        ["preset.copilotChatVsCode.reason"] = "GitHub Copilot Chat state and command data inside VS Code.",
        ["preset.gitconfig.name"] = "Git config",
        ["preset.gitconfig.reason"] = "User-level Git configuration.",
        ["preset.gitignoreGlobal.name"] = "Git global ignore",
        ["preset.gitignoreGlobal.reason"] = "User-level Git ignore rules shared across repositories.",
        ["preset.gitConfigDir.name"] = "Git config directory",
        ["preset.gitConfigDir.reason"] = "Git XDG-style user configuration directory.",
        ["preset.npmrc.name"] = "npm config",
        ["preset.npmrc.reason"] = "User-level npm configuration.",
        ["preset.yarnrc.name"] = "Yarn config",
        ["preset.yarnrc.reason"] = "User-level Yarn configuration.",
        ["preset.yarnrcYml.name"] = "Yarn Berry config",
        ["preset.yarnrcYml.reason"] = "User-level Yarn 2+ YAML configuration.",
        ["preset.pnpmrc.name"] = "pnpm config",
        ["preset.pnpmrc.reason"] = "User-level pnpm configuration when stored separately from npm.",
        ["preset.mcpJson.name"] = "MCP config",
        ["preset.mcpJson.reason"] = "User-level MCP server configuration.",
        ["preset.pipConfig.name"] = "pip config",
        ["preset.pipConfig.reason"] = "Python pip user-level configuration, such as indexes and proxy settings.",
        ["preset.uvConfig.name"] = "uv config",
        ["preset.uvConfig.reason"] = "uv user-level configuration for Python package and tool workflows.",
        ["preset.nugetConfig.name"] = "NuGet config",
        ["preset.nugetConfig.reason"] = "NuGet user-level package source and restore configuration.",
        ["preset.mavenSettings.name"] = "Maven settings",
        ["preset.mavenSettings.reason"] = "Maven user-level settings, mirrors, proxies, and repository preferences.",
        ["preset.gradleProperties.name"] = "Gradle properties",
        ["preset.gradleProperties.reason"] = "Gradle user-level build properties.",
        ["preset.gradleInit.name"] = "Gradle init scripts",
        ["preset.gradleInit.reason"] = "Gradle user-level initialization scripts.",
        ["preset.cargoConfig.name"] = "Cargo config",
        ["preset.cargoConfig.reason"] = "Rust Cargo user-level configuration.",
        ["preset.bunfig.name"] = "Bun config",
        ["preset.bunfig.reason"] = "Bun user-level runtime and package manager configuration.",
        ["preset.powershell.name"] = "PowerShell profile",
        ["preset.powershell.reason"] = "PowerShell profile scripts and module configuration.",
        ["preset.windowsPowerShell.name"] = "Windows PowerShell profile",
        ["preset.windowsPowerShell.reason"] = "Windows PowerShell profile scripts and module configuration.",
        ["preset.windowsTerminal.name"] = "Windows Terminal",
        ["preset.windowsTerminal.reason"] = "Windows Terminal settings and local state.",
        ["preset.windowsTerminalPreview.name"] = "Windows Terminal Preview",
        ["preset.windowsTerminalPreview.reason"] = "Windows Terminal Preview settings and local state.",
        ["preset.windowsTerminalCanary.name"] = "Windows Terminal Canary",
        ["preset.windowsTerminalCanary.reason"] = "Windows Terminal Canary settings and local state.",
        ["preset.windowsTerminalUnpackaged.name"] = "Windows Terminal unpackaged",
        ["preset.windowsTerminalUnpackaged.reason"] = "Windows Terminal settings for unpackaged installations.",
        ["preset.neovimConfig.name"] = "Neovim config",
        ["preset.neovimConfig.reason"] = "Neovim user configuration on Windows.",
        ["preset.vimfiles.name"] = "Vim files",
        ["preset.vimfiles.reason"] = "Vim user plugins and configuration files.",
        ["preset.vimrc.name"] = "Vim _vimrc",
        ["preset.vimrc.reason"] = "Vim user-level Windows configuration file.",
        ["preset.dotVimrc.name"] = "Vim .vimrc",
        ["preset.dotVimrc.reason"] = "Vim user-level configuration file used by cross-platform dotfiles.",
        ["preset.starship.name"] = "Starship prompt",
        ["preset.starship.reason"] = "Starship prompt user-level TOML configuration.",
        ["preset.alacritty.name"] = "Alacritty",
        ["preset.alacritty.reason"] = "Alacritty terminal configuration on Windows.",
        ["preset.weztermLua.name"] = "WezTerm config file",
        ["preset.weztermLua.reason"] = "WezTerm home-directory Lua configuration file.",
        ["preset.weztermConfig.name"] = "WezTerm config directory",
        ["preset.weztermConfig.reason"] = "WezTerm multi-file configuration directory.",
        ["preset.nushell.name"] = "Nushell",
        ["preset.nushell.reason"] = "Nushell config.nu, env.nu, and related startup configuration.",
        ["preset.jetbrains.name"] = "JetBrains",
        ["preset.jetbrains.reason"] = "JetBrains IDE settings, plugins, and application state.",
        ["preset.clashVerge.name"] = "Clash Verge",
        ["preset.clashVerge.reason"] = "Clash Verge profiles and application configuration."
    };

    private static readonly Dictionary<string, string> Zh = new()
    {
        ["app.title"] = "Link Shelf",
        ["app.startupFailed"] = "程序启动失败，已写入启动错误日志。",
        ["app.cannotLocateSelf"] = "无法定位当前程序，不能自动请求管理员权限。",
        ["app.adminRequired"] = "需要管理员权限才能移动目录和创建链接。",

        ["main.cacheRoot"] = "缓存根目录：{0}",
        ["main.configFile"] = "配置文件：{0}",
        ["main.add"] = "添加项目",
        ["main.addRecommended"] = "添加推荐项目",
        ["main.addDirectory"] = "添加目录",
        ["main.addFile"] = "添加文件",
        ["main.restore"] = "恢复链接",
        ["main.check"] = "检查状态",
        ["main.revert"] = "搬回原位/撤销",
        ["main.project"] = "投射程序",
        ["main.language"] = "语言",
        ["language.en"] = "英语",
        ["language.zh"] = "中文",
        ["main.log"] = "操作日志",
        ["help.add"] = "把选择的文件或目录移动到当前缓存根目录，并在原位置创建链接。",
        ["help.addRecommended"] = "从本机已检测到的常见配置和状态路径中选择要加入的项目。",
        ["help.addDirectory"] = "把选择的目录移动到当前缓存根目录，并在原位置创建链接。",
        ["help.addFile"] = "把选择的文件移动到当前缓存根目录，并在原位置创建链接。",
        ["help.restore"] = "根据配置创建本机链接。选中多行时，只处理选中的项目。",
        ["help.check"] = "只检查配置、缓存项目和目标链接是否匹配，不移动文件。",
        ["help.revert"] = "把选中的缓存项目搬回原始位置，移除原路径链接，从缓存中删除对应项目，并删除配置记录。",
        ["help.project"] = "在另一个目录中创建 LinkShelf.exe 的硬链接。从那个目录启动时，链接程序会把那个目录作为独立缓存根目录。",

        ["grid.cacheName"] = "缓存名称",
        ["grid.originalPath"] = "原始位置",
        ["grid.type"] = "类型",
        ["grid.status"] = "状态",
        ["grid.checkResult"] = "检查结果",
        ["grid.sourceMachine"] = "来源机器",
        ["grid.lastOperation"] = "最近操作",
        ["grid.updatedAt"] = "更新时间",
        ["grid.cachePath"] = "缓存路径",
        ["grid.localTarget"] = "本机目标",

        ["dialog.pickDirectory"] = "选择要移入缓存的目录",
        ["dialog.pickFile"] = "选择要移入缓存的文件",
        ["dialog.pickProjectionDirectory"] = "选择要投射 Link Shelf 的目录",
        ["dialog.noItems"] = "配置文件中还没有同步项目。",
        ["dialog.noSelection"] = "请先选择一个或多个项目。",
        ["dialog.restoreSelected"] = "将恢复选中的 {0} 项。",
        ["dialog.restoreAll"] = "将恢复全部启用项。",
        ["dialog.restoreConfirmSuffix"] = "遇到冲突时会逐项询问。",
        ["dialog.revertConfirm"] = "确定将选中的 {0} 项搬回原始位置并删除配置记录吗？搬回后，对应缓存项会从缓存目录中消失。",
        ["recommended.title"] = "推荐项目",
        ["recommended.heading"] = "添加推荐项目",
        ["recommended.description"] = "这里只显示本机存在、并且还没有写入配置文件的常见配置和状态路径。",
        ["recommended.select"] = "添加",
        ["recommended.name"] = "名称",
        ["recommended.path"] = "路径",
        ["recommended.type"] = "类型",
        ["recommended.reason"] = "推荐理由",
        ["recommended.addSelected"] = "添加选中项",
        ["recommended.noItems"] = "当前没有可添加的推荐项目。已配置的路径和本机不存在的路径会被自动隐藏。",
        ["recommended.noSelection"] = "请先选择一个或多个推荐项目。",
        ["dialog.lockedPathTitle"] = "路径被占用",
        ["dialog.lockedPathMessage"] = "添加操作失败，这个路径可能正在被其他程序占用。{0}{0}路径：{0}{1}{0}{0}错误：{0}{2}{0}{0}检测到的程序：{0}{3}{0}{0}请先关闭上方列出的软件，然后点击“确定”重新扫描并继续。点击“取消”会停止本次添加。",
        ["dialog.lockedPathPreflightMessage"] = "这个路径看起来正在被其他程序占用。{0}{0}路径：{0}{1}{0}{0}检测到的程序：{0}{2}{0}{0}请先关闭上方列出的软件，然后点击“确定”重新扫描并继续。点击“取消”会停止本次添加。",
        ["dialog.lockedPathNoProcesses"] = "没有检测到明确的占用程序。这个路径仍可能被权限、安全软件或正在运行的程序阻止。",
        ["dialog.lockedPathTimedOut"] = "占用扫描超时，尚未得到完整结果。",
        ["dialog.accessDeniedTitle"] = "访问被拒绝",
        ["dialog.accessDeniedMessage"] = "Windows 在移动这个路径时拒绝访问。{0}{0}路径：{0}{1}{0}{0}错误：{0}{2}{0}{0}这通常表示目录有受保护权限、相关服务正在保护它，或 Windows 拒绝移动其中的某些内容。请关闭相关软件和服务，或者改为移动更小的子目录。",
        ["lockWindow.title"] = "处理文件占用",
        ["lockWindow.heading"] = "操作失败，正在检测占用这个路径的进程。",
        ["lockWindow.path"] = "路径：{0}",
        ["lockWindow.error"] = "Windows 错误：{0}",
        ["lockWindow.scanning"] = "正在获取占用信息",
        ["lockWindow.noProcesses"] = "没有找到占用进程。",
        ["lockWindow.foundProcesses"] = "找到 {0} 个占用进程。",
        ["lockWindow.scanFailed"] = "获取占用信息失败：{0}",
        ["lockWindow.processName"] = "进程",
        ["lockWindow.processId"] = "进程号",
        ["lockWindow.user"] = "用户",
        ["lockWindow.executable"] = "程序路径",
        ["lockWindow.terminateSelected"] = "结束选中进程",
        ["lockWindow.refresh"] = "重新检测",
        ["lockWindow.terminateAllContinue"] = "结束全部并继续",
        ["lockWindow.terminating"] = "正在结束进程",
        ["lockWindow.terminateConfirmTitle"] = "结束进程",
        ["lockWindow.terminateConfirm"] = "确定结束 {0} 个进程吗？这些程序中未保存的内容可能会丢失。",
        ["lockWindow.terminateFailed"] = "结束进程失败：{0}",

        ["conflict.title"] = "处理冲突",
        ["conflict.heading"] = "目标位置存在冲突",
        ["conflict.target"] = "目标位置：{0}",
        ["conflict.cache"] = "缓存位置：{0}",
        ["conflict.useCache"] = "使用缓存目录里的内容",
        ["conflict.useTarget"] = "使用原位置里的内容",
        ["conflict.merge"] = "先保留两边内容，再尽量合并",
        ["conflict.skip"] = "先备份原位置内容，这次不处理",
        ["conflict.cancel"] = "取消",

        ["log.started"] = "程序已启动。",
        ["log.begin"] = "开始：{0}",
        ["log.done"] = "完成：{0}",
        ["log.failed"] = "失败：{0}，{1}",
        ["log.retryLockedPath"] = "用户处理占用后重试：{0}",
        ["log.lockedPathCanceled"] = "已取消被占用路径操作：{0}",
        ["log.projected"] = "已投射程序链接：{0}",
        ["projection.created"] = "已创建投射的 LinkShelf.exe：{0}。从这个链接程序启动时，会使用它所在目录作为独立缓存根目录。",
        ["projection.cannotLocateSelf"] = "无法定位当前程序。",
        ["projection.error.sameExecutable"] = "选择的目录就是当前程序所在位置。",
        ["projection.error.targetExists"] = "选择的目录已经包含 LinkShelf.exe。Link Shelf 不会覆盖它。",
        ["projection.error.differentDrive"] = "投射程序使用硬链接，因此目标目录必须和当前 LinkShelf.exe 在同一个盘符下。",
        ["projection.error.nativeFailure"] = "Windows 创建投射硬链接失败：{0}",
        ["op.addDirectory"] = "添加目录",
        ["op.addFile"] = "添加文件",
        ["op.addRecommendedItem"] = "添加推荐项目：{0}",
        ["op.restoreLinks"] = "恢复链接",
        ["op.checkStatus"] = "检查状态",
        ["op.revertItems"] = "搬回原位/撤销",

        ["code.directory"] = "目录",
        ["code.file"] = "文件",
        ["code.enabled"] = "启用",
        ["code.removed"] = "已移除",
        ["code.problem"] = "异常",
        ["code.symbolic-link"] = "符号链接",
        ["code.ok"] = "链接正常",
        ["code.cache-missing"] = "缓存项不存在",
        ["code.target-has-content"] = "目标被真实内容占用",
        ["code.target-missing-link"] = "目标缺少链接",
        ["code.link-wrong-target"] = "链接指向其他位置",
        ["code.skipped"] = "已跳过",
        ["code.restored"] = "已恢复",
        ["code.add-sync-item"] = "添加同步项",
        ["code.complete-existing-link"] = "补全配置",
        ["code.restore-local-link"] = "恢复本机链接",
        ["code.revert-item"] = "搬回原位/撤销",
        ["code.cache-already-exists"] = "缓存目录中已经存在同名项目。",
        ["code.target-is-another-link"] = "目标位置已经是指向其他位置的链接。",
        ["code.target-has-real-content"] = "目标位置已经有真实内容。",

        ["preset.codex.name"] = "Codex",
        ["preset.codex.reason"] = "Codex 的设置和代理工作流本地状态。",
        ["preset.claude.name"] = "Claude",
        ["preset.claude.reason"] = "Claude Code 的设置和本地状态。",
        ["preset.claudeJson.name"] = "Claude JSON",
        ["preset.claudeJson.reason"] = "Claude Code 的用户级配置文件。",
        ["preset.claudeDesktop.name"] = "Claude Desktop",
        ["preset.claudeDesktop.reason"] = "Claude Desktop 的设置、MCP 配置和本地应用状态。",
        ["preset.claudeDesktopMsix.name"] = "Claude Desktop MSIX",
        ["preset.claudeDesktopMsix.reason"] = "新版 Windows 打包安装的 Claude Desktop 设置和 MCP 配置位置。",
        ["preset.gemini.name"] = "Gemini",
        ["preset.gemini.reason"] = "Gemini CLI 的设置和本地状态。",
        ["preset.continue.name"] = "Continue",
        ["preset.continue.reason"] = "Continue.dev 的助手配置、模型设置、规则和本地状态。",
        ["preset.aiderConfig.name"] = "aider 配置",
        ["preset.aiderConfig.reason"] = "aider 的用户级 YAML 配置。",
        ["preset.windsurfMcp.name"] = "Windsurf MCP",
        ["preset.windsurfMcp.reason"] = "Windsurf Cascade 的 MCP 配置和相关 Codeium 状态。",
        ["preset.windsurfUser.name"] = "Windsurf 用户设置",
        ["preset.windsurfUser.reason"] = "Windsurf 编辑器的设置、快捷键、代码片段和用户状态。",
        ["preset.cursorProfile.name"] = "Cursor 配置目录",
        ["preset.cursorProfile.reason"] = "用户目录下的 Cursor 配置和状态数据。",
        ["preset.cursorUser.name"] = "Cursor 用户设置",
        ["preset.cursorUser.reason"] = "Cursor 的设置、快捷键、代码片段和用户状态。",
        ["preset.cursorBackups.name"] = "Cursor 备份",
        ["preset.cursorBackups.reason"] = "Cursor 的工作区备份数据。",
        ["preset.cursorWorkspaces.name"] = "Cursor 工作区",
        ["preset.cursorWorkspaces.reason"] = "Cursor 的工作区元数据。",
        ["preset.cursorDictionaries.name"] = "Cursor 词典",
        ["preset.cursorDictionaries.reason"] = "Cursor 的自定义词典。",
        ["preset.clineCursor.name"] = "Cursor 中的 Cline",
        ["preset.clineCursor.reason"] = "Cursor 内 Cline 扩展的状态和任务历史。",
        ["preset.rooCursor.name"] = "Cursor 中的 Roo Code",
        ["preset.rooCursor.reason"] = "Cursor 内 Roo Code 扩展的状态、模式、设置和任务历史。",
        ["preset.vscodeProfile.name"] = "VS Code 配置目录",
        ["preset.vscodeProfile.reason"] = "用户目录下的 VS Code 扩展和配置数据。",
        ["preset.vscodeUser.name"] = "VS Code 用户设置",
        ["preset.vscodeUser.reason"] = "VS Code 的设置、快捷键、代码片段和用户状态。",
        ["preset.vscodeInsidersProfile.name"] = "VS Code Insiders 配置目录",
        ["preset.vscodeInsidersProfile.reason"] = "用户目录下的 VS Code Insiders 扩展和配置数据。",
        ["preset.vscodeInsidersUser.name"] = "VS Code Insiders 用户设置",
        ["preset.vscodeInsidersUser.reason"] = "VS Code Insiders 的设置、快捷键、代码片段和用户状态。",
        ["preset.vscodiumProfile.name"] = "VSCodium 配置目录",
        ["preset.vscodiumProfile.reason"] = "用户目录下的 VSCodium 扩展和配置数据。",
        ["preset.vscodiumUser.name"] = "VSCodium 用户设置",
        ["preset.vscodiumUser.reason"] = "VSCodium 的设置、快捷键、代码片段和用户状态。",
        ["preset.clineVsCode.name"] = "VS Code 中的 Cline",
        ["preset.clineVsCode.reason"] = "VS Code 内 Cline 扩展的状态和任务历史。",
        ["preset.rooVsCode.name"] = "VS Code 中的 Roo Code",
        ["preset.rooVsCode.reason"] = "VS Code 内 Roo Code 扩展的状态、模式、设置和任务历史。",
        ["preset.copilotVsCode.name"] = "VS Code 中的 GitHub Copilot",
        ["preset.copilotVsCode.reason"] = "VS Code 内 GitHub Copilot 扩展的本地状态。",
        ["preset.copilotChatVsCode.name"] = "VS Code 中的 GitHub Copilot Chat",
        ["preset.copilotChatVsCode.reason"] = "VS Code 内 GitHub Copilot Chat 的状态和命令数据。",
        ["preset.gitconfig.name"] = "Git 配置",
        ["preset.gitconfig.reason"] = "用户级 Git 配置。",
        ["preset.gitignoreGlobal.name"] = "Git 全局忽略",
        ["preset.gitignoreGlobal.reason"] = "跨仓库共享的用户级 Git 忽略规则。",
        ["preset.gitConfigDir.name"] = "Git 配置目录",
        ["preset.gitConfigDir.reason"] = "Git 的 XDG 风格用户配置目录。",
        ["preset.npmrc.name"] = "npm 配置",
        ["preset.npmrc.reason"] = "用户级 npm 配置。",
        ["preset.yarnrc.name"] = "Yarn 配置",
        ["preset.yarnrc.reason"] = "用户级 Yarn 配置。",
        ["preset.yarnrcYml.name"] = "Yarn Berry 配置",
        ["preset.yarnrcYml.reason"] = "Yarn 2 及以上版本的用户级 YAML 配置。",
        ["preset.pnpmrc.name"] = "pnpm 配置",
        ["preset.pnpmrc.reason"] = "单独保存时的用户级 pnpm 配置。",
        ["preset.mcpJson.name"] = "MCP 配置",
        ["preset.mcpJson.reason"] = "用户级 MCP 服务器配置。",
        ["preset.pipConfig.name"] = "pip 配置",
        ["preset.pipConfig.reason"] = "Python pip 的用户级配置，例如源和代理设置。",
        ["preset.uvConfig.name"] = "uv 配置",
        ["preset.uvConfig.reason"] = "uv 在 Python 包和工具工作流中的用户级配置。",
        ["preset.nugetConfig.name"] = "NuGet 配置",
        ["preset.nugetConfig.reason"] = "NuGet 的用户级包源和还原配置。",
        ["preset.mavenSettings.name"] = "Maven 设置",
        ["preset.mavenSettings.reason"] = "Maven 的用户级设置、镜像、代理和仓库偏好。",
        ["preset.gradleProperties.name"] = "Gradle 属性",
        ["preset.gradleProperties.reason"] = "Gradle 的用户级构建属性。",
        ["preset.gradleInit.name"] = "Gradle 初始化脚本",
        ["preset.gradleInit.reason"] = "Gradle 的用户级初始化脚本。",
        ["preset.cargoConfig.name"] = "Cargo 配置",
        ["preset.cargoConfig.reason"] = "Rust Cargo 的用户级配置。",
        ["preset.bunfig.name"] = "Bun 配置",
        ["preset.bunfig.reason"] = "Bun 的用户级运行时和包管理配置。",
        ["preset.powershell.name"] = "PowerShell 配置",
        ["preset.powershell.reason"] = "PowerShell 配置脚本和模块配置。",
        ["preset.windowsPowerShell.name"] = "Windows PowerShell 配置",
        ["preset.windowsPowerShell.reason"] = "Windows PowerShell 配置脚本和模块配置。",
        ["preset.windowsTerminal.name"] = "Windows Terminal",
        ["preset.windowsTerminal.reason"] = "Windows Terminal 的设置和本地状态。",
        ["preset.windowsTerminalPreview.name"] = "Windows Terminal Preview",
        ["preset.windowsTerminalPreview.reason"] = "Windows Terminal Preview 的设置和本地状态。",
        ["preset.windowsTerminalCanary.name"] = "Windows Terminal Canary",
        ["preset.windowsTerminalCanary.reason"] = "Windows Terminal Canary 的设置和本地状态。",
        ["preset.windowsTerminalUnpackaged.name"] = "未打包版 Windows Terminal",
        ["preset.windowsTerminalUnpackaged.reason"] = "未打包安装的 Windows Terminal 设置。",
        ["preset.neovimConfig.name"] = "Neovim 配置",
        ["preset.neovimConfig.reason"] = "Windows 上的 Neovim 用户配置。",
        ["preset.vimfiles.name"] = "Vim 文件",
        ["preset.vimfiles.reason"] = "Vim 用户插件和配置文件。",
        ["preset.vimrc.name"] = "Vim _vimrc",
        ["preset.vimrc.reason"] = "Vim 在 Windows 上的用户级配置文件。",
        ["preset.dotVimrc.name"] = "Vim .vimrc",
        ["preset.dotVimrc.reason"] = "跨平台 dotfiles 常用的 Vim 用户级配置文件。",
        ["preset.starship.name"] = "Starship 提示符",
        ["preset.starship.reason"] = "Starship 提示符的用户级 TOML 配置。",
        ["preset.alacritty.name"] = "Alacritty",
        ["preset.alacritty.reason"] = "Alacritty 终端在 Windows 上的配置。",
        ["preset.weztermLua.name"] = "WezTerm 配置文件",
        ["preset.weztermLua.reason"] = "WezTerm 放在用户目录下的 Lua 配置文件。",
        ["preset.weztermConfig.name"] = "WezTerm 配置目录",
        ["preset.weztermConfig.reason"] = "WezTerm 的多文件配置目录。",
        ["preset.nushell.name"] = "Nushell",
        ["preset.nushell.reason"] = "Nushell 的 config.nu、env.nu 和相关启动配置。",
        ["preset.jetbrains.name"] = "JetBrains",
        ["preset.jetbrains.reason"] = "JetBrains IDE 的设置、插件和应用状态。",
        ["preset.clashVerge.name"] = "Clash Verge",
        ["preset.clashVerge.reason"] = "Clash Verge 的订阅、配置和应用状态。"
    };
}
